export const APP_FEATURES =[
    {
        id: "01",
        title: "Tailored Just for you",
        description: "Get Interview questions and model answer based on your role., experience, and specific focus area-"
    },
    {
        id: "02",
        title: "Learn at your own pace",
        description: "Expand answer only when you are ready. Dive deeper into any concept instantly with AI- powered detailed"
    },
    {
        id: "03",
        title : "Capture Your Insights",
        description: "Add personal notes to my question and pin important ones to the top - making your learning more organized"
    },
    {
        id: "04",
        title: 'Understand the "Why" Behind answers',
        description: "Beyond just answers - unlock detailed concept explanations generated by AI, helping you truly master eaxh concept "
    },
    {
        id: "05",
        title: "Save, Organize, and Revisit",
        description :"Easily save your interview sets, organize them neatly in your dashboard, and pickup your preparation"
    }
];